name = "FastPerms"
uuid = "4f7ee846-71eb-4ef0-b8b4-b98ea9e842ee"
authors = ["Bui Quang Minh <minhcly95@outlook.com> and contributors"]
version = "0.3.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
